config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :products
  resources :orders
  resources :brands
  root to: "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  has_and_belongs_to_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :products, through: :order_detail, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  #validations
  validates :name, :description, :brand_id, :user_id, :category_id, presence: true
  validates :name, length: { minimum: 5 }

  #relationships
  has_one_attached :photo
  belongs_to :brand
  belongs_to :category
  belongs_to :user
  has_many :orders, through: :order_detail, dependent: :destroy
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy

  enum rol: [:seller, :admin]
  #after_initialize :set_default_rol, :if => :new_record?
  #def set_default_rol
    #self.rol ||= :visit
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :configure_permitted_parameters, if: :devise_controller?

  #protected

  #def configure_permitted_parameters
    #devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  #end

  def user_admin
    if !current_user.admin?
      redirect_to products_path, alert: "You do not have permission for this action"
    end
  end

  def create_products
    if !current_user.seller?
      redirect_to products_path, alert: "You do not have permission for this action"
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :user_admin, except: %i[ index ]

  def index
    @brands = Brand.all
  end

  def show
    brand
  end


  def new
    # @brand = current_user.brands.build
    @brand = Brand.new
  end

  def edit
    brand
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to brands_path, notice: "brand was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if brand.update(brand_params)
      redirect_to brands_path, notice: "brand was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    brand.destroy

    redirect_to brands_url, notice: "brand was successfully destroyed."
  end

  private
    def brand
      @brand = Brand.find(params[:id])
    end

    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :user_admin, except: %i[ index ]

  def index
    @categories = Category.all
  end

  def show
    category
  end

  def new
    @category = Category.new
  end

  def edit
    category
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: "Category was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if category.update(category_params)
      redirect_to categories_path, notice: "Category was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    category.destroy

    redirect_to categories_path, notice: "Category was successfully destroyed."
  end

  private
    def category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = Order.all
  end

  def show
    order
  end


  def new
    # @order = current_user.orders.build
    @order = Order.new
  end

  def edit
    order
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to orders_path, notice: "order was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if order.update(order_params)
      redirect_to orders_path, notice: "order was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    order.destroy

    redirect_to orders_url, notice: "order was successfully destroyed."
  end

  private
    def order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :create_products, except: %i[ index show ]
  before_action :set_product, only: %i[ show edit update destroy ]
  #before_action :create_products, except: %i[ index show ]

  # GET /products or /products.json
  def index
    @categories = Category.all
    @products = Product.all
    if params[:category_id]
      @products = @products.where(category_id: params[:category_id])
    end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :brand_id, :category_id, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/_brand.html.erb
<div id="<%= dom_id brand %>">
  <p>
    <strong>Name:</strong>
    <%= brand.name %>
  </p>
</div>

app/views/brands/_form.html.erb
<%= form_with(model: brand) do |form| %>
  <% if brand.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= link_to "Show this brand", @brand %> |
  <%= link_to "Back to brands", brands_path %>
</div>

app/views/brands/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Brands</h1>

<div id="brands">
  <% @brands.each do |brand| %>
    <%= render brand %>
    <p>
      <%= link_to "Show this brand", brand %>
    </p>
  <% end %>
</div>

<%= link_to "New brand", new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= link_to "Back to brands", brands_path %>
</div>

app/views/brands/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @brand %>

<div>
  <%= link_to "Edit this brand", edit_brand_path(@brand) %> |
  <%= link_to "Back to brands", brands_path %>

  <%= button_to "Destroy this brand", @brand, method: :delete %>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Category:</strong>
    <%= category.name %>
  </p>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<%= link_to "New category", new_category_path %>
<br>
<br>

<div id="categories">
  <% @categories.each do |category| %>

    <%= render category %>
    <%= link_to "Show this category", category %>

  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Name:</strong>
    <%= order.name %>
  </p>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id) do %>
  <%= category.name %>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :brand_id, style: "display: block" %>
    <%= form.collection_select :brand_id, Brand.all, :id, :name, include_blank: true %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, include_blank: true %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.file_field :photo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= product.brand.name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category.name %>
  </p>
  <% if product.photo.attached? %>
    <%= image_tag product.photo, width: 150 %>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<%= render partial: 'category', collection: @categories %>

<% if user_signed_in? %>
  <% if current_user.rol == "admin" %>
    <%= link_to 'Categories', categories_path %>
  <% else %>
  <% end %>
<% end %>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <article id="article">
      <h2><%= product.name %></h2>
      <% if product.photo.attached? %>
        <%= image_tag product.photo, width: 150 %>
      <% end %>

      <footer class="footer">
        <span>Category: <%= product.category.name %></span>
        <span>Brand: <%= product.brand.name %></span>
        <%= link_to "Show this product", product %>
      </footer>
    </article>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="container">
  <ul>
    <li><%= link_to "🏠", root_path %></li>
    <li><%= link_to "Listado de Productos", products_path %></li>
  </ul>
  <ul>
    <% if user_signed_in? %>
      <% if current_user.rol == "seller" %>
        <li><%= link_to "Publicar un producto", new_product_path %></li>
      <% else %>
        no puede Publicar
      <% end %>
      <li><strong><%= current_user.email %></strong></li>
      <li><%= link_to "Realizar Pedido", new_order_path %></li>
      <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
      <li><%= link_to "Cerrar sesion", destroy_user_session_path, 'data-turbo-method': :delete %></li>
    <% else %>
      <li><%= link_to "Inicia sesion", new_user_session_path %></li>
      <li><%= link_to "Registrate", new_user_registration_path %></li>
    <% end %>
  </ul>
</nav>